#:kivy 1.8.0

<LevelButton>:

    background_color: (1,1,1,.5)

    canvas:
        Rectangle:
            texture: self.custom_texture
            pos: self.x+(self.width/2.0)-(48+24), self.y+(self.height/2.0)-(48+24+12)
            size: 96+48,96+48+24


    Label:
        id: score
        center: root.x+(root.width/2.0), root.y+(root.height/2.0)
        text: 'LOCKED'



            


        